#!/usr/bin/env python3
"""
export_model.py

Export a trained sklearn OneClassSVM to C header files for bare-metal inference.

Usage:
    python export_model.py --model model.pkl --scaler scaler.pkl --output ocsvm_model.h

Or call export_ocsvm_to_c() directly from your notebook after training.

The generated ocsvm_model.h replaces the one in ocsvm_baremetal/ and is
immediately usable with ocsvm_inference.h + ocsvm_baremetal.c.
"""

import argparse
import numpy as np


def export_ocsvm_to_c(clf, scaler=None, output_path="ocsvm_model.h"):
    """
    Export a trained sklearn OneClassSVM (with RBF kernel) to a C header file.

    Parameters
    ----------
    clf : sklearn.svm.OneClassSVM
        Trained model. Must use kernel='rbf'.
    scaler : sklearn.preprocessing.MinMaxScaler or None
        If provided, exports scaler parameters too.
    output_path : str
        Path to write the .h file.
    """

    # Validate
    if clf.kernel != 'rbf':
        raise ValueError(f"Only RBF kernel supported, got '{clf.kernel}'")

    # Extract model parameters
    sv = clf.support_vectors_          # shape: (n_sv, n_features)
    dual_coef = clf.dual_coef_[0]      # shape: (n_sv,)
    intercept = clf.intercept_[0]      # scalar (rho)
    n_sv, n_features = sv.shape

    # Compute effective gamma
    if clf.gamma == 'scale':
        gamma = 1.0 / (n_features * clf._gamma)  # sklearn stores computed gamma
    elif clf.gamma == 'auto':
        gamma = 1.0 / n_features
    else:
        gamma = clf.gamma

    # Use the internally computed gamma if available
    if hasattr(clf, '_gamma'):
        gamma = clf._gamma

    with open(output_path, 'w') as f:
        f.write("/*\n")
        f.write(f" * {output_path}\n")
        f.write(f" * Auto-generated by export_model.py\n")
        f.write(f" *\n")
        f.write(f" * Model: OneClassSVM (RBF kernel)\n")
        f.write(f" *   Support vectors: {n_sv}\n")
        f.write(f" *   Features:        {n_features}\n")
        f.write(f" *   Gamma:           {gamma}\n")
        f.write(f" *   Intercept (rho): {intercept}\n")
        f.write(f" */\n\n")

        f.write("#ifndef OCSVM_MODEL_H\n")
        f.write("#define OCSVM_MODEL_H\n\n")

        # Dimensions
        f.write(f"#define N_SUPPORT_VECTORS  {n_sv}\n")
        f.write(f"#define N_FEATURES          {n_features}\n\n")

        # Kernel parameters
        f.write(f"#define OCSVM_GAMMA       {gamma}f\n")
        f.write(f"#define OCSVM_INTERCEPT   {intercept}f\n\n")

        # Support vectors
        f.write(f"static const float support_vectors[N_SUPPORT_VECTORS][N_FEATURES] = {{\n")
        for i, vec in enumerate(sv):
            vals = ", ".join(f"{v}f" for v in vec)
            comma = "," if i < n_sv - 1 else ""
            f.write(f"    {{ {vals} }}{comma}\n")
        f.write("};\n\n")

        # Dual coefficients
        f.write(f"static const float dual_coefs[N_SUPPORT_VECTORS] = {{\n")
        for i, c in enumerate(dual_coef):
            comma = "," if i < n_sv - 1 else ""
            f.write(f"    {c}f{comma}\n")
        f.write("};\n\n")

        # Scaler parameters
        if scaler is not None:
            scale_vals = scaler.scale_
            min_vals = scaler.min_  # sklearn's min_ = -data_min * scale

            f.write("/* MinMaxScaler: scaled[i] = raw[i] * scaler_scale[i] + scaler_min[i] */\n")

            f.write(f"static const float scaler_min[N_FEATURES] = {{\n    ")
            f.write(", ".join(f"{v}f" for v in min_vals))
            f.write("\n};\n\n")

            f.write(f"static const float scaler_scale[N_FEATURES] = {{\n    ")
            f.write(", ".join(f"{v}f" for v in scale_vals))
            f.write("\n};\n\n")
        else:
            f.write("/* No scaler exported — define your own scaler_min/scaler_scale */\n")
            f.write(f"static const float scaler_min[N_FEATURES] = {{ {', '.join(['0.0f'] * n_features)} }};\n")
            f.write(f"static const float scaler_scale[N_FEATURES] = {{ {', '.join(['1.0f'] * n_features)} }};\n\n")

        f.write("#endif /* OCSVM_MODEL_H */\n")

    print(f"Exported OCSVM model to {output_path}")
    print(f"  {n_sv} support vectors x {n_features} features")
    print(f"  gamma = {gamma}, intercept = {intercept}")
    if scaler is not None:
        print(f"  Scaler parameters included")


def export_ocsvm_flat_score_function(clf, scaler=None, output_path="ocsvm_score_flat.h"):
    """
    Export the OCSVM as a single flat score() function (like the existing
    ocsvm_detector.c), useful for comparing against the table-based version.

    This produces a monolithic expression identical in structure to the
    score() function in the original ocsvm_detector.c.
    """

    sv = clf.support_vectors_
    dual_coef = clf.dual_coef_[0]
    intercept = clf.intercept_[0]
    n_sv, n_features = sv.shape

    if hasattr(clf, '_gamma'):
        gamma = clf._gamma
    else:
        gamma = clf.gamma

    with open(output_path, 'w') as f:
        f.write("/* Auto-generated flat score function */\n\n")
        f.write(f"static float flat_score(float *input) {{\n")
        f.write(f"    return {intercept}f")

        for i in range(n_sv):
            f.write(f"\n        + fast_expf(-{gamma}f * (")
            terms = []
            for j in range(n_features):
                terms.append(f"({sv[i][j]}f - input[{j}]) * ({sv[i][j]}f - input[{j}])")
            f.write(" + ".join(terms))
            f.write(f")) * {dual_coef[i]}f")

        f.write(";\n}\n")

    print(f"Exported flat score function to {output_path}")


# ---- CLI entry point ----
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export OCSVM to C header")
    parser.add_argument("--model", required=True, help="Path to pickled OneClassSVM (.pkl)")
    parser.add_argument("--scaler", default=None, help="Path to pickled MinMaxScaler (.pkl)")
    parser.add_argument("--output", default="ocsvm_model.h", help="Output .h file path")
    parser.add_argument("--flat", action="store_true", help="Also export flat score function")
    args = parser.parse_args()

    import pickle

    with open(args.model, 'rb') as f:
        clf = pickle.load(f)

    scaler = None
    if args.scaler:
        with open(args.scaler, 'rb') as f:
            scaler = pickle.load(f)

    export_ocsvm_to_c(clf, scaler, args.output)

    if args.flat:
        flat_path = args.output.replace(".h", "_flat.h")
        export_ocsvm_flat_score_function(clf, scaler, flat_path)
