/*
 * ocsvm_baremetal.c — SoCurity Baremetal
 *
 * Bare-metal OCSVM anomaly detector for the SoCurity tile on ESP+x-heep.
 *
 * ---- SoCurity tile architecture ----
 * This firmware runs on the Ibex (SoCurity Core) inside the SoCurity tile,
 * which is an x-heep native tile modified for security monitoring:
 *
 *   SoCurity Core (Ibex)  ←→  X-Heep OBI System Bus (xbar)
 *                                   |
 *              ┌────────────────────┼──────────────────────┐
 *              ↓                    ↓                      ↓
 *   APB-to-NoC (obi_to_esp)  SoCurity IRQ Handler   X-Heep peripherals
 *   [reads monitor regs       [writes IRQ over         (UART, timers…)
 *    from all other tiles      NoC plane 6 →
 *    via NoC plane 5/6]        Ariane on anomaly]
 *
 * Monitor reading path:
 *   Ibex → OBI xbar → demux → obi_to_esp (Burst CSRs) → NoC plane 5 →
 *   target tile's monitor MMIO registers → back to Ibex
 *   ESP monitor addresses are in the upper address range of the Ibex's
 *   memory map (above local SRAM), configured by esp-xconfig.
 *
 * Anomaly signaling path:
 *   Ibex writes to SoCurity IRQ Handler MMIO register →
 *   IRQ Handler sends interrupt over NoC plane 6 → Ariane IRQ line →
 *   SoCurity ISR on Ariane reads anomaly details.
 *
 * ---- Integration with x-heep ----
 * Place this file (along with ocsvm_model.h, ocsvm_inference.h, crt0.S) into:
 *   esp-heep/soft/common/apps/baremetal/ocsvm_detector/
 * Build via the SoCurity Bootloader flow (replaces xheep_boot_controller).
 *
 * ---- Feature mapping (from ocsvm_detector.c get_features()) ----
 *   feature[0] = ddr_accesses[0]            (DDR access count, tile 0)
 *   feature[1] = mem_reqs[0].coh_rsps_snd   (coherence responses sent, tile 0)
 *   feature[2] = mem_reqs[0].dma_reqs       (DMA requests, tile 0)
 *   feature[3] = noc_injects[4][4]          (NoC injections, plane 4 tile 4)
 *   feature[4] = sum of acc_stats[0..2].acc_tot  (accelerator total cycles, accs 0-2)
 *   feature[5] = sum of acc_stats[3..5].acc_tot  (accelerator total cycles, accs 3-5)
 */

#include <stdint.h>
#include <stddef.h>
#include "ocsvm_platform.h"
#include "ocsvm_inference.h"

/* =========================================================================
 * Platform configuration — ADJUST THESE for your specific SoC
 *
 * After running `make esp-xconfig` and generating your SoC, find the exact
 * addresses in:
 *   $DESIGN_PATH/socgen/esp/esp_global.h
 *   $DESIGN_PATH/socgen/esp/socmap.vhd
 *
 * Base addresses are taken from ocsvm_platform.h.
 * Defaults preserve current behavior and can be overridden by generated SoC
 * headers or build flags.
 * ========================================================================= */

/* --- ESP Monitor MMIO base address --- */
/* Each tile has a bank of 59 monitor counters, each 32 bits.
 * The base address comes from the ESP address map generated by esp-xconfig.
 * Check: grep -r "MON_BASE" $DESIGN_PATH/socgen/ */

/* --- Monitor layout --- */
#define COUNTERS_PER_TILE     59    /* ESP has 59 counters per tile */
#define MON_TILE_STRIDE       (COUNTERS_PER_TILE * 4)  /* bytes between tiles */

/* --- Monitor counter indices (from ESP Monitors API) ---
 * These index into the per-tile counter bank.
 * Ref: esp/soft/common/drivers/common/monitors/monitors.h
 */
#define MON_DDR_ACCESSES      0     /* DDR access count */
#define MON_COH_RSPS_SND      2     /* Coherence responses sent */
#define MON_DMA_REQS          5     /* DMA requests */
#define MON_NOC_INJECT_BASE   23    /* NoC injection counters (6 planes) */
/* Accelerator stats start at index 13, with 6 counters per accelerator:
 *   [13] = acc_tlb, [14] = acc_mem, [15] = acc_tot_lo,
 *   [16] = acc_tot_hi, [17] = acc_invocations, [18] = other
 * For acc N: base index = 13 + N*6 */
#define MON_ACC_STATS_BASE    13
#define MON_ACC_TOT_LO_OFF    2     /* offset from acc base to acc_tot_lo */
#define MON_ACC_TOT_HI_OFF    3     /* offset from acc base to acc_tot_hi */

/* --- Tile indices for feature extraction ---
 * Adjust these to match which tile/accelerator your training data used.
 * From ocsvm_detector.c: ddr_accesses[0], mem_reqs[0], noc_injects[4][4] */
#define DDR_TILE_ID           0     /* tile index for DDR/memory features */
#define NOC_INJECT_TILE       4     /* tile for NoC injection feature */
#define NOC_INJECT_PLANE      4     /* NoC plane for injection feature */

/* --- UART for debug output ---
 * x-heep uses the OpenTitan UART IP. Register layout (from uart_regs.h):
 *   +0x00  INTR_STATE
 *   +0x0C  CTRL         — baud rate, TX/RX enable
 *   +0x10  STATUS       — bit 0 = txfull, bit 2 = txempty
 *   +0x1C  WDATA        — write one byte here to enqueue for TX
 *
 * The UART base address in esp-heep is set by the SoC address map.
 * Check: grep -r "UART" $DESIGN_PATH/socgen/esp/esp_global.h
 *        or x-heep/hw/ip/uart/data/uart_regs.h
 */
#define UART_STATUS_OFFSET    0x10          /* STATUS register */
#define UART_TX_FULL_BIT      (1U << 0)    /* bit 0: TX FIFO full */
#define UART_WDATA_OFFSET     0x1C         /* TX data register */

/* --- SoCurity IRQ Handler ---
 * The SoCurity IRQ Handler is a new peripheral on the x-heep OBI peripheral bus.
 * The Ibex writes to it when an anomaly is detected; the hardware then sends an
 * interrupt packet over ESP NoC plane 6 to Ariane.
 *
 * Register map offsets are defined in ocsvm_platform.h.
 *
 * The base address is assigned when you add the SoCurity IRQ Handler to x-heep's
 * peripheral bus. Check: grep "SOCURITY" $DESIGN_PATH/socgen/esp/esp_global.h
 * or look in x-heep/hw/ip/socurity_irq/data/socurity_irq_regs.h after RTL integration.
 *
 * Until the RTL is integrated, you can substitute x-heep's existing fast_intr_ctrl
 * (fast interrupt controller) to signal the local Ibex, and separately use a shared
 * DRAM flag that Ariane polls. See TODO below.
 */
/* Shared DRAM flag (interim approach before SoCurity IRQ Handler RTL is done):
 * Ariane writes a known physical address here at boot that the Ibex polls and
 * Ariane reads. Until then, use UART output as the only signaling path. */
/* --- Timing --- */
#define DETECTION_INTERVAL    100000  /* ~100ms worth of loop iterations */


/* =========================================================================
 * MMIO helpers
 * ========================================================================= */

static inline uint32_t mmio_read32(uint32_t addr)
{
    return *((volatile uint32_t *)addr);
}

static inline void mmio_write32(uint32_t addr, uint32_t val)
{
    *((volatile uint32_t *)addr) = val;
}

static inline uint32_t socurity_alert_read(uint32_t reg_offset)
{
    return mmio_read32(SOCURITY_ALERT_BASE + reg_offset);
}

static inline void socurity_alert_write(uint32_t reg_offset, uint32_t value)
{
    mmio_write32(SOCURITY_ALERT_BASE + reg_offset, value);
}

/* =========================================================================
 * UART output (minimal bare-metal)
 * ========================================================================= */

static void uart_putc(char c)
{
    /* Busy-wait until TX FIFO is not full (x-heep OpenTitan UART).
     * STATUS register bit 0 = txfull; spin until it clears. */
    while (mmio_read32(UART_BASE + UART_STATUS_OFFSET) & UART_TX_FULL_BIT)
        __asm__ volatile("nop");
    mmio_write32(UART_BASE + UART_WDATA_OFFSET, (uint32_t)c);
}

static void uart_puts(const char *s)
{
    while (*s) {
        if (*s == '\n') uart_putc('\r');
        uart_putc(*s++);
    }
}

/* Minimal integer-to-string for printing scores */
static void uart_print_int(int32_t val)
{
    char buf[12];
    int i = 0;
    uint32_t uval;

    if (val < 0) {
        uart_putc('-');
        uval = (uint32_t)(-(val + 1)) + 1;
    } else {
        uval = (uint32_t)val;
    }

    if (uval == 0) {
        uart_putc('0');
        return;
    }

    while (uval > 0) {
        buf[i++] = '0' + (uval % 10);
        uval /= 10;
    }
    while (--i >= 0) {
        uart_putc(buf[i]);
    }
}

/* Print float with 4 decimal places (good enough for scores) */
static void uart_print_float(float val)
{
    if (val < 0.0f) {
        uart_putc('-');
        val = -val;
    }
    int32_t integer_part = (int32_t)val;
    float frac = val - (float)integer_part;
    int32_t frac_part = (int32_t)(frac * 10000.0f);

    uart_print_int(integer_part);
    uart_putc('.');
    /* Leading zeros for fractional part */
    if (frac_part < 1000) uart_putc('0');
    if (frac_part < 100)  uart_putc('0');
    if (frac_part < 10)   uart_putc('0');
    uart_print_int(frac_part);
}


/* =========================================================================
 * ESP Monitor reading — direct MMIO
 *
 * Each tile's monitor bank is at:
 *   ESP_MON_BASE_ADDR + tile_id * MON_TILE_STRIDE + counter_idx * 4
 * ========================================================================= */

static inline uint32_t read_monitor(int tile_id, int counter_idx)
{
    uint32_t addr = ESP_MON_BASE_ADDR
                  + (uint32_t)tile_id * MON_TILE_STRIDE
                  + (uint32_t)counter_idx * 4;
    return mmio_read32(addr);
}

typedef struct {
    uint8_t tile_id;
    uint8_t monitor_idx;
} monitor_tap_t;

typedef struct {
    uint8_t tile_id;
    uint8_t acc_idx;
} acc_tap_t;

static const monitor_tap_t FEATURE_MONITOR_TAPS[4] = {
    { DDR_TILE_ID, MON_DDR_ACCESSES },
    { DDR_TILE_ID, MON_COH_RSPS_SND },
    { DDR_TILE_ID, MON_DMA_REQS },
    { NOC_INJECT_TILE, (uint8_t)(MON_NOC_INJECT_BASE + NOC_INJECT_PLANE) },
};

static const acc_tap_t FEATURE4_ACC_TAPS[] = {
    { DDR_TILE_ID, 0 },
    { DDR_TILE_ID, 1 },
    { DDR_TILE_ID, 2 },
};

static const acc_tap_t FEATURE5_ACC_TAPS[] = {
    { DDR_TILE_ID, 3 },
    { DDR_TILE_ID, 4 },
    { DDR_TILE_ID, 5 },
};

static inline uint32_t read_tap_monitor(const monitor_tap_t *tap)
{
    if ((int)tap->tile_id >= N_TILES) {
        return 0;
    }
    return read_monitor((int)tap->tile_id, (int)tap->monitor_idx);
}

static inline uint64_t read_acc_total(int tile_id, int acc_idx);

static uint64_t read_acc_group_total(const acc_tap_t *taps, size_t ntaps)
{
    uint64_t total = 0;
    size_t i;

    for (i = 0; i < ntaps; i++) {
        if ((int)taps[i].tile_id >= N_TILES) {
            continue;
        }
        total += read_acc_total((int)taps[i].tile_id, (int)taps[i].acc_idx);
    }

    return total;
}

/* Read 64-bit accelerator total (composed from hi/lo 32-bit registers) */
static inline uint64_t read_acc_total(int tile_id, int acc_idx)
{
    int base_idx = MON_ACC_STATS_BASE + acc_idx * 6;
    uint32_t lo = read_monitor(tile_id, base_idx + MON_ACC_TOT_LO_OFF);
    uint32_t hi = read_monitor(tile_id, base_idx + MON_ACC_TOT_HI_OFF);
    return ((uint64_t)hi << 32) | (uint64_t)lo;
}


/* =========================================================================
 * Feature extraction — mirrors ocsvm_detector.c get_features()
 *
 * Takes delta between two snapshots and produces the 6-element feature vector.
 * ========================================================================= */

typedef struct {
    uint32_t ddr_accesses;
    uint32_t coh_rsps_snd;
    uint32_t dma_reqs;
    uint32_t noc_inject;
    uint64_t acc_tot_012;  /* sum of acc 0,1,2 total cycles */
    uint64_t acc_tot_345;  /* sum of acc 3,4,5 total cycles */
} monitor_snapshot_t;

static void take_snapshot(monitor_snapshot_t *snap)
{
    snap->ddr_accesses = read_tap_monitor(&FEATURE_MONITOR_TAPS[0]);
    snap->coh_rsps_snd = read_tap_monitor(&FEATURE_MONITOR_TAPS[1]);
    snap->dma_reqs     = read_tap_monitor(&FEATURE_MONITOR_TAPS[2]);
    snap->noc_inject   = read_tap_monitor(&FEATURE_MONITOR_TAPS[3]);

    /* Accelerator totals are map-driven for easy retargeting across SoCs. */
    snap->acc_tot_012  = read_acc_group_total(FEATURE4_ACC_TAPS,
                                              sizeof(FEATURE4_ACC_TAPS) / sizeof(FEATURE4_ACC_TAPS[0]));
    snap->acc_tot_345  = read_acc_group_total(FEATURE5_ACC_TAPS,
                                              sizeof(FEATURE5_ACC_TAPS) / sizeof(FEATURE5_ACC_TAPS[0]));
}

static void compute_features(const monitor_snapshot_t *prev,
                              const monitor_snapshot_t *curr,
                              float *features)
{
    features[0] = (float)(curr->ddr_accesses - prev->ddr_accesses);
    features[1] = (float)(curr->coh_rsps_snd - prev->coh_rsps_snd);
    features[2] = (float)(curr->dma_reqs     - prev->dma_reqs);
    features[3] = (float)(curr->noc_inject   - prev->noc_inject);
    features[4] = (float)(curr->acc_tot_012  - prev->acc_tot_012);
    features[5] = (float)(curr->acc_tot_345  - prev->acc_tot_345);
}


/* =========================================================================
 * Delay loop (no OS timer available in bare-metal)
 *
 * For more precise timing, configure the RISC-V machine timer (mtime/mtimecmp)
 * or use x-heep's timer peripheral.
 * ========================================================================= */

static void delay_loop(volatile uint32_t count)
{
    while (count-- > 0) {
        __asm__ volatile("nop");
    }
}

static void socurity_irq_selftest(void)
{
#if SOCURITY_ENABLE_IRQ_SELFTEST
    uint32_t before_status;
    uint32_t trigger_val;
    uint32_t status_after_trigger;
    uint32_t iter_after_trigger;
    uint32_t status_after_clear;

    before_status = socurity_alert_read(SOCURITY_ALERT_STATUS);
    trigger_val = 0x534F4300UL;

    socurity_alert_write(SOCURITY_ALERT_CLEAR, 1U);
    socurity_alert_write(SOCURITY_ALERT_TRIGGER, trigger_val);

    status_after_trigger = socurity_alert_read(SOCURITY_ALERT_STATUS);
    iter_after_trigger = socurity_alert_read(SOCURITY_ALERT_ITERATION);

    socurity_alert_write(SOCURITY_ALERT_CLEAR, 1U);
    status_after_clear = socurity_alert_read(SOCURITY_ALERT_STATUS);

    uart_puts("[socurity-irq-selftest] before=");
    uart_print_int((int32_t)before_status);
    uart_puts(" pending=");
    uart_print_int((int32_t)(status_after_trigger & 1U));
    uart_puts(" iter=");
    uart_print_int((int32_t)iter_after_trigger);
    uart_puts(" after_clear=");
    uart_print_int((int32_t)(status_after_clear & 1U));
    uart_puts("\n");
#endif
}


/* =========================================================================
 * Main — anomaly detection loop
 * ========================================================================= */

int main(void)
{
    monitor_snapshot_t snap_prev, snap_curr;
    float features[N_FEATURES];
    float score_val;
    int prediction;
    uint32_t iteration = 0;

    uart_puts("=== OCSVM Bare-Metal Anomaly Detector ===\n");
    uart_puts("Model: 33 SVs, 6 features, gamma=2.723\n");
    uart_puts("Starting detection loop...\n\n");

    socurity_irq_selftest();

    /* Initial snapshot */
    take_snapshot(&snap_prev);

    /* Wait one interval before first detection */
    delay_loop(DETECTION_INTERVAL);

    /* Main detection loop */
    while (1) {
        /* Take new snapshot */
        take_snapshot(&snap_curr);

        /* Compute feature deltas */
        compute_features(&snap_prev, &snap_curr, features);

        /* Scale features (in-place) */
        min_max_scale(features);

        /* Run OCSVM inference */
        score_val  = ocsvm_score(features);
        prediction = (score_val > 0.0f) ? 0 : 1;

        /* Report result */
        uart_puts("[");
        uart_print_int((int32_t)iteration);
        uart_puts("] ");
        uart_puts(ocsvm_label(prediction));
        uart_puts(" (score=");
        uart_print_float(score_val);
        uart_puts(")\n");

        if (prediction == 1) {
            uart_puts("*** ANOMALY DETECTED ***\n");

            /*
             * Signal anomaly to Ariane via the SoCurity IRQ Handler peripheral.
             *
             * Writing the iteration number to ALERT_TRIGGER causes the SoCurity
             * IRQ Handler hardware to:
             *   1. Latch the iteration number into ALERT_ITERATION (readable by Ariane)
             *   2. Send an interrupt packet over ESP NoC plane 6 to the Ariane tile
             *
             * On Ariane, the corresponding IRQ line triggers the SoCurity ISR which
             * reads ALERT_ITERATION and logs the event.
             *
             * The write can be disabled at compile time with:
             *   -DSOCURITY_ENABLE_ALERT_TRIGGER=0
             */
#if SOCURITY_ENABLE_ALERT_TRIGGER
            socurity_alert_write(SOCURITY_ALERT_TRIGGER, iteration);
#endif

            /*
             * Interim: write a flag to shared DRAM that Ariane polls.
             * Ariane must map this physical address before the Ibex boots.
             * TODO: uncomment after coordinating the shared address with Ariane.
             */
            /* mmio_write32(SOCURITY_SHARED_FLAG_ADDR, iteration); */
        }

        /* Rotate snapshots */
        snap_prev = snap_curr;
        iteration++;

        /* Wait before next sample */
        delay_loop(DETECTION_INTERVAL);
    }

    /* Never reached */
    return 0;
}
